Quiron.LojaVirtual.Web/Controllers/CarrinhoController.cs
using System;
using System.Configuration;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Quiron.LojaVirtual.Dominio.Entidade;
using Quiron.LojaVirtual.Dominio.Repositorio;
using Quiron.LojaVirtual.Web.Models;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class CarrinhoController : Controller
    {
        private ProdutosRepositorio _repositorio;

        public RedirectToRouteResult Adicionar( Carrinho carrinho, int produtoId,int quantidade, string returnUrl)
        {
            _repositorio = new ProdutosRepositorio();

            Produto produto = _repositorio.Produtos.
                FirstOrDefault(p => p.ProdutoId == produtoId);

            if (produto != null)
            {
                // ObterCarrinho().AdicionarItem(produto, 1);
                carrinho.AdicionarItem(produto, quantidade);
            }

            return RedirectToAction("Index", new { returnUrl });

        }

        //private Carrinho ObterCarrinho()
        //{
        //    Carrinho carrinho = (Carrinho)Session["Carrinho"];

        //    if (carrinho == null)
        //    {
        //        carrinho = new Carrinho();
        //        Session["Carrinho"] = carrinho;
        //    }

        //    return carrinho;
        //}

        public RedirectToRouteResult Remover(Carrinho carrinho, int produtoId, string returnUrl)
        {

            _repositorio = new ProdutosRepositorio();

            Produto produto = _repositorio.Produtos
                .FirstOrDefault(p => p.ProdutoId == produtoId);

            if (produto != null)
            {

               // ObterCarrinho().RemoverItem(produto);
                carrinho.RemoverItem(produto);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Index(Carrinho carrinho, string returnurl)
        {
            return View(new CarrinhoViewModel
            {
                Carrinho = carrinho,
                ReturnUrl = returnurl
            });
        }

        public PartialViewResult Resumo(Carrinho carrinho)
        {
          // Carrinho carrinho = ObterCarrinho();
            return PartialView(carrinho);
        }


        public ViewResult FecharPedido()
        {
            return View(new Pedido());
        }


        [HttpPost]
        public ViewResult FecharPedido( Carrinho carrinho, Pedido pedido)
        {
          //  Carrinho carrinho = ObterCarrinho();

            EmailConfiguracoes email = new EmailConfiguracoes
            {
                EscreverArquivo = bool.Parse(ConfigurationManager.AppSettings["Email.EscreverArquivo"] ?? "false")
            };

            EmailPedido emailPedido = new EmailPedido(email);

            if (!carrinho.ItensCarrinho.Any())
            {
                ModelState.AddModelError("", "Não foi possível concluir o pedido, seu carrinho está vazio!");
            }

            if (ModelState.IsValid)
            {
                emailPedido.ProcessarPedido(carrinho, pedido);
                carrinho.LimparCarrino();
                return View("PedidoConcluido");
            }
            else
            {
                return View(pedido);
            }

        }

        public ViewResult PedidoConcluido()
        {
            return View();
        }

    }
}

Quiron.LojaVirtual.Web/Controllers/VitrineController.cs
using System.Linq;
using System.Web.Mvc;
using Quiron.LojaVirtual.Dominio.Repositorio;
using Quiron.LojaVirtual.Dominio.Entidade;
using Quiron.LojaVirtual.Web.Models;
using System;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class VitrineController : Controller
    {
        private ProdutosRepositorio _repositorio;
        public int ProdutosPorPagina = 12;


        //public ViewResult ListaProdutos(string categoria, int pagina = 1)
        //{
        //    _repositorio = new ProdutosRepositorio();

        //    ProdutosViewModel model = new ProdutosViewModel
        //    {

        //        Produtos = _repositorio.Produtos
        //            .Where(p => categoria == null || p.Categoria == categoria)
        //            .OrderBy(p => p.Descricao)
        //            .Skip((pagina - 1) * ProdutosPorPagina)
        //            .Take(ProdutosPorPagina),



        //      paginacao = new Paginacao

        //        {
        //            PaginaAtual = pagina,
        //            ItensPorPagina = ProdutosPorPagina,
        //            ItensTotal = categoria == null ? _repositorio.Produtos.Count() : _repositorio.Produtos.Count(e => e.Categoria == categoria)
        //        },

        //        CategoriaAtual = categoria
        //    };


        //    return View(model);
        //}

        [Route("DetalhesProduto/{id}/{produto}")]
        public ViewResult Detalhes(int id)
        {

            _repositorio = new ProdutosRepositorio();
            Produto produto = _repositorio.ObterProduto(id);
            return View(produto);


        }


        public ViewResult ListaProdutos(string categoria)
        {
            _repositorio = new ProdutosRepositorio();

            var model = new ProdutosViewModel();
            var rnd = new Random();

            if (categoria != null)
            {
                model.Produtos = _repositorio.Produtos
                    .Where(p => p.Categoria == categoria)
                    .OrderBy(x => rnd.Next()).ToList();
            }
            else
            {
                model.Produtos = _repositorio.Produtos
                    .OrderBy(x => rnd.Next())
                    .Take(ProdutosPorPagina).ToList();
            }



            return View(model);
        }

        [Route("Vitrine/ObterImagem/{produtoId}")]
        public FileContentResult ObterImagem(int produtoId)
        {

            _repositorio = new ProdutosRepositorio();
            Produto prod = _repositorio.Produtos
                .FirstOrDefault(p => p.ProdutoId == produtoId);

            if (prod != null)
            {
                return File(prod.Imagem, prod.ImagemMimeType);
            }

            return null;

        }
    }
            

}

Quiron.LojaVirtual.Web/Views/Shared/ProdutoDetalhes.cshtml
@model Quiron.LojaVirtual.Dominio.Entidade.Produto


<div class="well">

    @if (Model.Imagem != null)
    {

        <div class="row">

            <div class="pull-left" style="margin-right: 10px">

                <img class="img-thumbnail" width="120" height="120" src="@Url.Action("ObterImagem", "Vitrine", new { Model.ProdutoId })" />

            </div>


        </div>
    }




    <div class="row">

        <h4>
            @Html.ActionLink(@Model.Nome, "Detalhes", "Vitrine", new { id = @Model.ProdutoId, produto = @Model.Nome.ToString() }, new { @class = "deco-nome" })
            <br />
            <span class="pull-right label label-primary">@Model.Preco.ToString("c")</span>
        </h4>


    </div>

</div>

Quiron.LojaVirtual.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Quiron Loja Virtual</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
  @* @Styles.Render("~/Content/css")*@
   
    

</head>
<body>


    <div class="navbar navbar-inverse" role="navigation" >
        <a class="navbar-brand" href="#">Quiron Loja Virtual - Seu esporte é aqui </a>
        @Html.Action("resumo", "Carrinho")
    </div>
   
    <div class="row panel">
        <div id="categorias" class="col-xs-3">
            @Html.Action("Menu","categoria")
        </div>


        <div id="categorias" class="col-xs-8">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryVal")
   

</body>



</html>